

version: "3.8"

services:
  # Bot service
  inhouse_bot:
    #image: mrtolkien/inhouse_bot
    environment:
      # The connection string is an SQLAlchemy connection string, does not need a password since it uses sockets
      INHOUSE_BOT_CONNECTION_STRING: postgresql+psycopg2://postgres:@/inhouse_bot

      # You need to put your Discord Bot token here
      INHOUSE_BOT_TOKEN: ODY0ODkxNTAxNTA3Mzc5MjUw.YO8C-g.fT4vJ5FzWP1lxhjGMdY7FcRT1_o


    volumes:
      # Socket volume to connect to the database
      - type: volume
        source: dbsocket
        target: /var/run/postgresql

    depends_on:
      - db

  # Database service for the bot
  db:
    image: postgres:alpine
    volumes:
      # Database persistence volume
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
      # Socket volume to communicate faster
      - type: volume
        source: dbsocket
        target: /var/run/postgresql
    environment:
      # CHANGE THE PASSWORD BEFORE DEPLOYMENT
      POSTGRES_PASSWORD: randompasswordlmao
      POSTGRES_DB: inhouse_bot

  # Simple database management tool (will use the password you set for the db service)
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080


volumes:
  pgdata:     # Persistent data volume for the database
  dbsocket:   # Socket mounting volume
